name: Build Go Project & Attach exe to release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            asset_name: ssc-linux-amd64
          - os: ubuntu-24.04-arm
            asset_name: ssc-linux-arm64
          - os: windows-2025
            asset_name: ssc-windows-amd64.exe

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'
        check-latest: true
        cache-dependency-path: "**/*.sum"

    - name: Build
      run: go build -v -o ssc
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ssc
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
